export {
  buildResumeOutline,
  docToText,
  findElement,
  findModule,
  findRow,
  genId,
  getDocTextAlign,
  normalizeResumeTargetId,
  normalizeResumeTargetIds,
  reindexOrder,
  textToDoc,
  withUpdatedElement,
  withUpdatedModule,
  type ElementLocation,
} from "@/lib/resume-core"
